# @package _global_
defaults:
  - /trainer: default
  - /loader: torch
  - /dataset: stocks-day
  - /task: regression
  - /optimizer: adamw
  - /scheduler: plateau

train:
  monitor: val/loss # Needed for plateau scheduler
  mode: min

encoder:
  - linear

decoder:
  _name_: sequence
  mode: last

trainer:
  val_check_interval: 0.2
