_name_: dlr
d_state: 4096
bidirectional: false
activation: gelu
postact: null
hyper_act: null
dropout: ${..dropout} # Same as null
trainable:
    Lambda: true
    W: true
lr:
    Lambda: 0.00005
    W: 0.00005
max_kernel_length: null
kernel_type: dlr
Lambda_init: omega
W_scale: null
pykeops: true
version: Lambda_imag_W_real
kernel_to_real: prod
l_max: ${oc.select:dataset.__l_max,1} # Grab dataset length if exists, otherwise set to 1 and kernel will automatically resize
verbose: false
